export const GET_SALES_ORDERS = "GET_SALES_ORDERS";
export const GET_SALES_ORDERS_ERR = "GET_SALES_ORDERS_ERR";
export const GET_USER_CART = "GET_USER_CART";
export const GET_USER_CART_ERR = "GET_USER_CART_ERR";
export const CART_ENTRIES_SUCCESS = "CART_ENTRIES_SUCCESS";
export const CART_ENTRIES_ERR= "CART_ENTRIES_ERR";

